version: '3.8'

services:
  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - static_data:/app/static
      - ./instance:/app/instance
    depends_on:
      - db
    networks:
      - vigiapp-network

  db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
    networks:
      - vigiapp-network

networks:
  vigiapp-network:
    driver: bridge

volumes:
  postgres_data:
  static_data: